### ISSUE TITLE
issue with ontology editor

### ISSUE THREAD

**Issue by luisenriqueramos1977** [GateNLP/gateplugin-Ontology_Tools#4] opened 2019-11-05 12:27 UTC
Dear friends of gate, 

I am trying to work with ontology plug in of gate, following the instructions of user manual Chapter 14. 

In section related with Ontology Annotation tool, when I try to apply it to my text, I select a text to include it as instance of ontology successfully, however the new instance is not highlighted in text, and it seems it should. 

Later, when I try to activate the RAT-C, and I receive an error:

Exception in thread "AWT-EventQueue-1" java.lang.IllegalAccessError: tried to access field gate.gui.docview.AbstractDocumentView.document from class gate.gui.docview.OntologyClassView$MouseStoppedMovingAction

However, I can see the the previously created instance as highlighted. Nevertheless, when I try to create a new instance following steps listed in 14.6.2, the New Inst button is disable, then I wonder if I am doing something wrong?, or if there is a bug in this process?. 

Best regards

Luis Ramos

**Comment by ianroberts** [comment] 2019-11-05 12:32
Duplicate of #3 

If the version of GATE you are running does not offer 8.6-SNAPSHOT by default then you can load it by clicking the `+` button at the top left of the plugin manager, and enter a group ID of `uk.ac.gate.plugins`, artifact ID `ontology-tools` and version `8.6-SNAPSHOT`

**Closed as completed by ianroberts** 2019-11-05 12:32 UTC
